# Generated by Django 4.0.4 on 2022-06-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category title')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.categorymodel')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color code')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color title')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/store/logo', verbose_name='Brand logo')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=512, null=True, verbose_name='Location title')),
                ('location_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Location link')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (-1, 'Deleted')], default=0, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (-1, 'Deleted')], default=0, verbose_name='Status')),
                ('people_type', models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Kids'), (-1, 'Not Selected')], default=-1, verbose_name='PeopleType')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='product', to='product.categorymodel', verbose_name='Categories')),
                ('colors', models.ManyToManyField(related_name='product', to='product.colormodel', verbose_name='Colors')),
                ('sizes', models.ManyToManyField(related_name='product', to='product.sizemodel', verbose_name='Sizes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.storemodel', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description for image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product images',
                'verbose_name_plural': 'Products images',
            },
        ),
    ]
