# Generated by Django 4.0.4 on 2022-06-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimagemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Products images'},
        ),
    ]
