# Generated by Django 4.0.4 on 2022-06-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimagemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='People type')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='people_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.peopletypemodel', verbose_name='Sizes'),
        ),
    ]
