# Generated by Django 4.0.4 on 2022-06-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_peopletypemodel_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='people_type',
        ),
        migrations.DeleteModel(
            name='PeopleTypeModel',
        ),
    ]
