# Generated by Django 4.0.4 on 2022-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productmodel_people_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'verbose_name': 'Product images', 'verbose_name_plural': 'Products images'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='people_type',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Kids'), (-1, 'Not Selected')], default=-1, verbose_name='PeopleType'),
        ),
    ]
