# Generated by Django 4.0.4 on 2022-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category/', verbose_name='category image'),
        ),
    ]
