# Generated by Django 4.0.4 on 2022-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Men'), (0, 'Women'), (2, 'Other')], default=2, verbose_name='GenderChoice'),
        ),
    ]
