# Generated by Django 4.0.4 on 2022-06-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_categorymodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Men'), (0, 'Women'), (2, 'Other')], default=2, verbose_name='GenderChoice'),
        ),
    ]
