# Generated by Django 4.0.4 on 2022-06-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_wishlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storemodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
