responses = {
    'EN': {
        'number_does_not_exist': 'Phone number does not exist.',
        'code_is_used': 'The provided code was used before.',
        'number_verified': 'Phone number verified successfully.',
        'invalid_code': 'The provided code did not match or has expired.',
        'user_not_found': 'User is not found.',
        'otp_is_sent': 'OTP sent successfully.',
        'otp_already_sent': 'The sms is already sent. It will be available in {} minute, {} seconds.',
        'number_exists': 'The user with the specified phone number has already been created.',
        'user_logged_out': 'User logged out successfully.',
        'token_blacklisted': 'Token is already blacklisted.',
        'logged_out_all_devices': 'Logged out from all devices successfully.',
        'district_not_found': 'District not found.',
        'region_not_found': 'Region not found.',
        'product_not_found': 'Product not found.',
        'showroom_not_found': 'Showroom not found.',
        'user_created': 'User is successfully created.',
        'product_deleted': 'Product is successfully deleted.',
        'do_not_have_permission': 'You do not have permission to perform this action.',
        'order_created': 'Order successfully created.',
        'user_deleted': 'User is successfully deleted.',
        'rate_created': 'Rate successfully created.',
        'rate_already_created': 'User has already rated this showroom',
        'password_not_match': 'Password fields did not match',
        'email_already_exists': 'User with this Email address already exists',
        'us_or_pass_incorrect': 'Incorrect username and/or password',
        'send_otp_error': "Error in sending OTP",
        'gender_value': "Gender value can be only 0 or 1!"

    },
    'RU': {
        'number_does_not_exist': 'Номер телефона не существует.',
        'code_is_used': 'Данный код уже был использован.',
        'number_verified': 'Номер телефона подтверждён успешно!',
        'invalid_code': 'Введён неправильный или не существующий код.',
        'user_not_found': 'Пользователь не найден.',
        'otp_is_sent': 'OTP отправлен успешно.',
        'otp_already_sent': 'OTP уже отправлен. Новый OTP можно отправить через {} минут, {} секунд.',
        'number_exists': 'Пользователь с данным номером телефона уже зарегистрирован.',
        'user_logged_out': 'Пользователь успешно вышел из системы.',
        'token_blacklisted': 'Токен уже перенесён в чёрный список.',
        'logged_out_all_devices': 'Во всех устройствах совершён выход из системы.',
        'district_not_found': 'Район не найден.',
        'region_not_found': 'Область не найдена.',
        'product_not_found': 'Продукт не найден.',
        'showroom_not_found': 'Выставочный зал не найден.',
        'user_created': 'Пользователь успешно зарегистрирован.',
        'product_deleted': 'Продукт успешно удален.',
        'do_not_have_permission': 'У вас нет разрешения на выполнение этого действия.',
        'order_created': 'Заказ успешно создан.',
        'user_deleted': 'Аккаунт успешно удален.',
        'rate_created': 'Оценка успешно оставлена.',
        'rate_already_created': "Пользователь уже оценил этот выставочный зал",
        'password_not_match': 'Поля пароля не совпадают',
        'email_already_exists': 'Пользователь с таким адресом электронной почты уже существует',
        'us_or_pass_incorrect': 'Неверное имя пользователя и/или пароль',
        'send_otp_error': 'Ошибка отправки OTP',
        'gender_value': "Значение пола может быть только 0 или 1!"
    },
    'UZ': {
        'number_does_not_exist': 'Telefon raqami mavjud emas.',
        'code_is_used': 'Ushbu kod oldin ishlatilingan.',
        'number_verified': 'Telefon raqami muvaffaqiyatli tarzda tasdiqlandi!',
        'invalid_code': 'Kiritilgan kod noto\'g\'ri yoki mavjud emas.',
        'user_not_found': 'Foydalanuvchi mavjud emas.',
        'otp_is_sent': 'OTP muvaffaqiyatli yuborildi.',
        'otp_already_sent': 'OTP yuborilgan. Yangi OTP\'ni {} daqiqa {} soniyadan so\'ng yuborish mumkin.',
        'number_exists': 'Ushbu telefon raqami bilan foydalanuvchi ro\'yxatdan o\'tgan.',
        'user_logged_out': 'Foydalanuvchi muvaffaqiyatli tarzda tizimdan chiqdi.',
        'token_blacklisted': 'Token allaqachon qora ro\'yxatga o\'tkazilgan.',
        'logged_out_all_devices': 'Barcha qurilmalarda dasturdan chiqildi.',
        'district_not_found': 'Tuman topilmadi.',
        'region_not_found': 'Viloyat topilmadi.',
        'showroom_not_found': "Ko'rgazma zali topilmadi.",
        'user_created': 'Foydalanuvchi muvaffaqiyatli tarzda ro\'yxatdan o\'tkazildi.',
        'product_deleted': 'Produkt muvaffaqiyatli tizimdan ochildi.',
        'product_not_found': 'Produkt topilmadi.',
        'do_not_have_permission': 'Sizda bu amalni bajarish uchun ruxsat yoq.',
        'order_created': 'Buyurtma muvaffaqiyatli yaratildi.',
        'user_deleted': "Foydalanuvchi muvaffaqiyatli tarzda tizimdan o'chirildi.",
        'rate_created': 'Izoh muvaffaqiyatli qoldirildi.',
        'rate_already_created': "Foydalanuvchi allaqachon ushbu ko'rgazma zalini baholagan",
        'password_not_match': 'Parol maydonlari mos kelmadi',
        'email_already_exists': 'Bu elektron pochta manziliga ega foydalanuvchi allaqachon mavjud',
        'us_or_pass_incorrect': "Noto'g'ri foydalanuvchi nomi va/yoki parol",
        'send_otp_error': "OTP yuborishda xatolik yuz berdi",
        'gender_value': "Jins qiymati faqat 0 yoki 1 bo'lishi mumkin!"
    },
}
