# Generated by Django 4.0.4 on 2022-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_city_usermodel_country_usermodel_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive'), (-1, 'Deleted')], default=0, null=True),
        ),
    ]
