# Generated by Django 4.0.4 on 2022-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default=112, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
