# Generated by Django 4.0.4 on 2022-06-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usermodel_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
    ]
