# Generated by Django 4.0.4 on 2022-06-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
    ]
