# Generated by Django 4.0.4 on 2022-06-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usermodel_groups_usermodel_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
