# Generated by Django 4.0.4 on 2022-06-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usermodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table=None,
        ),
    ]
