# Generated by Django 4.0.4 on 2022-06-04 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_productimagemodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.IntegerField(blank=True, null=True, verbose_name='Total product')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Total price')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description for order')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='text')),
                ('status', models.SmallIntegerField(choices=[(1, 'Accepted'), (0, 'Not Accepted'), (2, 'On The Way'), (-1, 'Deleted')], default=0, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User id')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='user id')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordermodel', verbose_name='order-items')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productmodel', verbose_name='order-items')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
