# Generated by Django 4.0.4 on 2022-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total product'),
        ),
    ]
