# Generated by Django 4.0.4 on 2022-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='product id'),
        ),
    ]
