# Generated by Django 4.0.4 on 2022-06-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitemmodel_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location of order'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User id'),
        ),
    ]
